### ISSUE TITLE
Invalid path alias: @supercool/tablemaker/assetbundles/field/dist

### ISSUE THREAD

**Issue by gglnx** [supercool/Table-Maker#29]
I think after moving the plugin the alias for assets must be updated too.

**Comment by engram-design** [comment]
Have you cleared you caches? There shouldn't be a reference to `@supercool/tablemaker/assetbundles` anywhere anymore, so where is that being called from?

**Comment by gglnx** [comment]
I've deleted all caches and since then the exception didn't occured again. I think this can be closed.
