### ISSUE TITLE
Table Maker is getting slow after 7-8 columns 

### ISSUE THREAD

**Issue by belkin** [supercool/Table-Maker#34]
### Describe the bug

Usually we have around 4 columns but in this particularly situation we need to use between 7-12 columns in matrix block. After adding so many columns and rows Table Maker is getting really slow. 

Is there anything that we can do about it? So the UI is not so 'laggy'? 

### Steps to reproduce

1. Create matrix field with Table Maker inside.
2. Add more than 7-8 columns (after 11 is getting really slow)
3. Start adding rows with content.

### Craft CMS version

4.3.6.1

### Plugin version

4.0.3

### Multi-site?

No

### Additional context

I'm also using Matrixmate for matrix block groups and tabs.

**Comment by engram-design** [comment]
I'm surprised that Table Maker is laggy, and how would you define slow? Is it the act of adding rows that's slow, or typing in a cell?

I've tested with a Matrix + Table Maker field just quickly, with 20 columns and 50 rows - all aspects of it seem fine to me.

Maybe a quick screen recording of the issue might help?

**Comment by belkin** [comment]
@engram-design sorry for the late response. Here is a video: https://youtu.be/p_PuoGQRwHU

I don't know if that is helpful information but I have also noticed that this happens when creating a new entry without anything else. After saving a draft or creating the entry it starts working properly for created columns. 

After creating a number of columns and you start with content filling (labels) then you need to wait for all the processing ..

**Comment by engram-design** [comment]
That's quite interesting, thanks for the video. Would there be any chance of getting a database backup of your site? Or an export of the Matrix field using [Field Manager](https://github.com/verbb/field-manager) so I can replicate? I have a feeling it might be very specific to your setup, so ideally if I can have the same field setup as yourself, that'd help.

If you can send anything through to `support@verbb.io` that would be amazing.

**Comment by belkin** [comment]
I have sent an export. Ticket ID: 648. Thanks for checking out.

**Comment by engram-design** [comment]
Thanks for that, that's been very helpful. Should be fixed in [4.0.4](https://github.com/verbb/tablemaker/releases/tag/4.0.4)

**Comment by belkin** [comment]
Great! Any idea when it'll be available for update?

**Comment by engram-design** [comment]
Hmmm, looks like it's not on the plugin store automatically. Will chase up with Craft support!
