### ISSUE TITLE
Unable to retrieve the column type using GraphQL

### ISSUE THREAD

**Issue by benfeather** [supercool/Table-Maker#40]
### What are you trying to do?

When retrieving values from the GraphQL API, it is not possible to determine the field type assigned to the column.

For example, if I have a table configured like this:
![CleanShot 2024-01-25 at 11 26 18@2x](https://github.com/verbb/tablemaker/assets/43571410/a2d22d27-21d2-4a0a-b140-29d4ab035abf)

And request the data using GraphQL, this is the response:
![CleanShot 2024-01-25 at 11 23 27@2x](https://github.com/verbb/tablemaker/assets/43571410/bab7b34d-27cf-42e0-bf59-a1ca770da37b)

### What's your proposed solution?

Add a "type" property to the table columns that outputs the field type. Using the example above, the output would be:

```
{
  "table": {
    "rows": [
      ["1", "1", "1", "1"],
      ["0", "0", "", ""]
    ],
    "columns": [
      {
        "heading": "Number",
        "type": "number"
      },
      {
        "heading": "Text",
        "type": "text"
      },
      {
        "heading": "Checkbox",
        "type": "checkbox"
      },
      {
        "heading": "Switch",
        "type": "switch"
      }
    ]
  }
}

**Comment by engram-design** [comment]
Added for the next release. To get this early, run `composer require verbb/tablemaker:"dev-craft-4 as 4.0.7"`.

**Comment by benfeather** [comment]
Legend. Works perfectly.
