### ISSUE TITLE
Deleting columns doesnt delete the rows, throws error on save

### ISSUE THREAD

**Issue by benfeather** [supercool/Table-Maker#41]
### Describe the bug

Suppose you create a table with columns and rows. If you delete a column(s), it is not deleted from the table rows, and when you save the entry, an error occurs.

Example (all columns have been deleted):
![CleanShot 2024-01-25 at 11 36 24@2x](https://github.com/verbb/tablemaker/assets/43571410/18627db2-ff73-4dee-bb8a-ae1eb5021c62)

Error on save:
![CleanShot 2024-01-25 at 11 37 47@2x](https://github.com/verbb/tablemaker/assets/43571410/77f95baa-a60c-40da-827d-f0a3d9dbb54c)

### Steps to reproduce

1. Create a table column
2. Create a row using that column
3. Delete the column
4. Save the entry

### Craft CMS version

4.7.0

### Plugin version

4.0.7

**Comment by engram-design** [comment]
Fixed for the next release. To get this early, run `composer require verbb/tablemaker:"dev-craft-4 as 4.0.7"`.

**Comment by benfeather** [comment]
Looks good, thanks!
