### ISSUE TITLE
Visual bug: Clicking column type input causes hidden button to pop in

### ISSUE THREAD

**Issue by benfeather** [supercool/Table-Maker#42]
### Describe the bug

Just a minor visual bug. When selecting the "column type" input, the "settings" button pops in, causing the inputs to be offset:

![CleanShot 2024-01-25 at 13 04 29@2x](https://github.com/verbb/tablemaker/assets/43571410/274c0eba-4908-48c6-a275-d1cd13b72757)

![CleanShot 2024-01-25 at 13 05 20@2x](https://github.com/verbb/tablemaker/assets/43571410/de607b1c-0462-4d20-91cf-6e1bf28b69c8)

### Steps to reproduce

1. Refresh an entry with the table field
2. Click the Table Columns "type" input. The invisible settings button will pop in.

### Craft CMS version

4.7.0

### Plugin version

4.0.6

### Multi-site?

Yes

**Comment by engram-design** [comment]
Fixed for the next release. To get this early, run `composer require verbb/tablemaker:"dev-craft-4 as 4.0.7"`.

**Comment by benfeather** [comment]
Looks good, thanks!
