### ISSUE TITLE
[Craft 4.6+] Dropdown columns lose options on save

### ISSUE THREAD

**Issue by andrewmenich** [supercool/Table-Maker#44]
### Describe the bug

When saving an entry with a table maker field containing columns with type "Dropdown", the options disappear and can no longer be selected unless you first open the column's settings modal. In the video below, I open the settings of the first column and click "Done", which prevents the options from disappearing on save while the rest of the dropdown fields have their options wiped. I dumped out the field value on the frontend and the previous values (rows) remained in tact, though the column options were indeed missing. 

https://github.com/verbb/tablemaker/assets/29585821/defb19d0-e1e0-499d-a825-a31f2b4d4189

This dump shows the field's "columns" options were removed after saved, except for the first column as demo'd in the video.
![SCR-20240325-ocnz](https://github.com/verbb/tablemaker/assets/29585821/1218dd96-02fc-4a33-8d63-f1ac6375bf39)

This dump shows that the values ("rows") remained in-tact despite the column options getting removed.
![SCR-20240325-ocpy](https://github.com/verbb/tablemaker/assets/29585821/7b10a97c-cf0d-4937-b76d-c9303cfbdf03)

I noticed this after updating the site's Craft & plugin and I was able to isolate it to Craft 4.6.0 (it works as expected on Craft 4.5.14 with Tablemaker versions 4.0.6, 4.0.7, and 4.0.8) but breaks as described above on Craft 4.6.0. I had a look at the changelog and suspect it's related to this update: https://github.com/craftcms/cms/issues/13852 Any help is greatly appreciated!

### Steps to reproduce

1. Update Craft to 4.6.0+
2. Resave an entry with a Tablemaker field containing a column of type Dropdown

### Craft CMS version

4.6.0

### Plugin version

4.0.9

### Multi-site?

No

**Comment by engram-design** [comment]
Yeah, looks like that Craft change might have something to do with it. Should be fixed in [4.0.10](https://github.com/verbb/tablemaker/releases/tag/4.0.10)
