### ISSUE TITLE
Undefined array key "type" on save

### ISSUE THREAD

**Issue by rwhisson** [supercool/Table-Maker#46]
### Describe the bug

I have just upgraded to 4.0.12 and I am now getting the error `Undefined array key "type"` on save. My field is added a block type within the Neo block type.

![image](https://github.com/user-attachments/assets/246e1357-f8c1-4b19-9142-3b236962ed9f)

I have rolled back to the previous version 4.0.11 which does not have this issue.

### Steps to reproduce

1. Click save

### Craft CMS version

4.11.1

### Plugin version

4.0.12

### Multi-site?

Yes

### Additional context

I am using the Neo plugin

**Comment by engram-design** [comment]
Fixed for the next release. To get this early, run `composer require verbb/tablemaker:"dev-craft-4 as 4.0.12"`.

**Comment by dlindberg** [comment]
Looks like Craft 5 has the same issue, (though line 204 on the Craft 5 branch).

**Comment by engram-design** [comment]
Fixed for the next release. To get this early, run `composer require verbb/tablemaker:"dev-craft-5 as 5.0.1"`.

**Comment by MattAppleton** [comment]
just to say – I noticed this error too, seems to be resolved if you add something — anything ! — into empty table cells...  its not a fix really but might help temporarily!

Running Craft 4.12.0 with Tablemaker 4.0.12

**Comment by engram-design** [comment]
Fixed in [4.0.13](https://github.com/verbb/tablemaker/releases/tag/4.0.13) and [5.0.2](https://github.com/verbb/tablemaker/releases/tag/5.0.2)
