### ISSUE TITLE
Table does not initialize, when in collapsed Matrix

### ISSUE THREAD

**Issue by vandres** [supercool/Table-Maker#47]
### Describe the bug

I am having an issue, when a table is placed in a Matrix and the editor collapsed the matrix blocks. I recorded a screen capture, for better understanding.

I have a workaround, which is a little annoying. When you expand the block and then save or refresh, then the table initializes after loading.

https://github.com/user-attachments/assets/c30d3da6-74f9-4cc9-8983-0a8f57358b83

### Steps to reproduce

1. Create a table
2. Place it in a Matrix block 
3. Collapse the block in an entry
4. Refresh
5. Expand the block
6. The table is not editable

Workaround:
7. Refresh or Save
8. Table is editable

### Craft CMS version

5.3.x

### Plugin version

5.0.1

### Multi-site?

yes

### Additional context

All dependencies:

```
 "craftcms/ckeditor": "^4.0.3",
        "craftcms/cms": "~5.3.0",
        "guzzlehttp/guzzle": "^7.8",
        "mmikkel/cp-field-inspect": "^2.0.1",
        "nystudio107/craft-retour": "^5.0.2",
        "nystudio107/craft-vite": "^5.0.0",
        "php-http/guzzle7-adapter": "^1.0",
        "putyourlightson/craft-elements-panel": "^3.0.0",
        "putyourlightson/craft-sprig": "^3.0.1",
        "spatie/craft-ray": "^2.0",
        "statikbe/craft-deepl": "^5.0@alpha",
        "vandres/craft-matrix-extended": "^3.1.0",
        "verbb/expanded-singles": "^3.0.0",
        "verbb/formie": "dev-craft-5 as 3.0.0-beta.18",
        "verbb/tablemaker": "^5.0.0",
        "vlucas/phpdotenv": "^5.5.0",
        "wbrowar/craft-admin-bar": "^5.0.0-beta.1"
```

**Comment by engram-design** [comment]
Fixed for the next release. To get this early, run `composer require verbb/tablemaker:"dev-craft-5 as 5.0.1"`.

**Comment by vandres** [comment]
Can confirm it's working. Thank you!
