### ISSUE TITLE
Email Validator not implemented

### ISSUE THREAD

**Issue by samuelreichor** [supercool/Table-Maker#48]
### Describe the bug

Hi, I have some troubles saving an entry with a table maker field in it because of Email Validation. 
I looked into `src/fields/TableMakerField.php` and it seems like the `EmailValidator` used in `_validateCellValue` is not even implemented.
Can you look into that and I would love to see a fix for Craft 4 as well because I'm not able to update to Craft 5 yet :(

### Steps to reproduce

1. Select Email As Column Type
2. Put an email into the row
3. Save Entry

### Craft CMS version

4.12.1

### Plugin version

4.0.13

### Multi-site?

Yes

**Comment by engram-design** [comment]
Fixed for the next release. To get this early, run `composer require verbb/tablemaker:"dev-craft-4 as 4.0.13"`.

**Comment by samuelreichor** [comment]
Thank u, works seamlessly 🚀

**Comment by engram-design** [comment]
Fixed in [4.0.14](https://github.com/verbb/tablemaker/releases/tag/4.0.14)
