### ISSUE TITLE
Possibility to add a hyper field to a row cell

### ISSUE THREAD

**Issue by lennonpuype** [supercool/Table-Maker#49]
### What are you trying to do?

It would be very handy to have the option to add a hyper field to a row cell. I had the exact use case for using this plugin, but there is one thing I am kinda stuck with to make this easy customisable by our client.

This way I can select an asset field or other types of links.

**What I need to have**
<img width="644" alt="Screenshot 2024-10-08 at 17 06 28" src="https://github.com/user-attachments/assets/1d907af0-37dd-47fa-95ae-f0275999b5ec">

**The table I can create**
![Screenshot 2024-10-08 at 17 12 28](https://github.com/user-attachments/assets/8a289b0a-f2ed-405e-bfe1-c15336440052)
I know the cell with text download should be a link, but it is just to visualise what I want 😉

### What's your proposed solution?

Adding the option for a hyper field when the plugin is installed.
Or an asset field for my usecase

**Comment by engram-design** [comment]
Having complex cells like this (and rich text) is _probably_ out of the realm of this plugin, at least without some major refactoring. Firstly, the UI is a challenge - how do we fit things in a small table cell? Secondly will be how we store content. Like the Craft Table field which isn't relational, we would have to change our handling into more like Super Table.

It's something lots of people want, but it's a bit of a challenge at the moment!

**Comment by lennonpuype** [comment]
Oh well I really understand that, certainly for the hyper side since it is a field that can be very advanced.
At least an asset field could really help the problem I have, but I'll look into another solution for this case.

Thx for the quick reply!
