### ISSUE TITLE
can craft 3.9.1can use this plugin ? 

### ISSUE THREAD

**Issue by abhitest** [supercool/Table-Maker#50]
### Question

how can i use this plugin for my project and also how can i make this work of 3.9.1

**Comment by engram-design** [comment]
While we don't [support](https://verbb.io/blog/craft-3-plugins) any Craft 3 plugins anymore, you can certainly keep using it.

At the time of writing, [3.0.4](https://github.com/verbb/tablemaker/releases/tag/3.0.4) works with Craft 3.7+.

Download and install the plugin as you would normally.

```
composer require verbb/tablemaker && php craft plugin/install tablemaker
```
